languageCode: "en-us"
title: "Lucas Menicucci"
theme: "anubis"
baseUrl: https://lsmenicucci.github.io/blog/
paginate: 10
enableRobotsTXT: true
publishDir: "docs"

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Lucas Menicucci"
  description: ""
  customCSS:
    - css/custom.css
  dateFormat: "02.01.2006"
  paginationSinglePost: true
  style: auto
  readMore: true
  social:
    - id: github
      name: lsmenicucci 

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
